### ISSUE TITLE
accidentally expanded collapsed cluster with double click, can't re-collapse it

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#111]
![screen shot 2017-10-23 at 11 46 33 am](https://user-images.githubusercontent.com/3842763/31898749-d8b69d90-b7e7-11e7-9689-59ecb6aef9e1.png)

java.lang.IllegalArgumentException: source node is not a member of this network
	at org.cytoscape.model.internal.SimpleNetwork.addEdgeInternal(SimpleNetwork.java:305)
	at org.cytoscape.model.internal.CyRootNetworkImpl.addEdge(CyRootNetworkImpl.java:374)
	at org.cytoscape.group.internal.CyGroupImpl.createMetaEdge(CyGroupImpl.java:1245)
	at org.cytoscape.group.internal.CyGroupImpl.collapse(CyGroupImpl.java:620)
	at org.cytoscape.group.internal.view.GroupViewDoubleClickListener$CollapseGroupTask.run(GroupViewDoubleClickListener.java:196)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:326)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
happens for every cluster I expand and then try to re-collapse.  Only way to rescue it is close session and re-collapse all clusters.

**Comment by mikekucera** [comment]
I think this is fixed in 3.6, will have to confirm
