### ISSUE TITLE
try to annotate a network whose similarities were created with overlap coef = 1 AA doesn't word

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#38]
Created EM with overlap coef threshold of 1
Try and autoannotate and nothing happens. 
I get the following stack:

```
Cytoscape 3.3.0> Task-Thread-15-Factory-0x7fc7ecc6 ERROR [TaskMonitor.org.cytoscape.command.internal.CommandStringsExecutorTask] - Error executing task: Error processing arguments: Couldn't parse value from: 1.0 for setting: edgeCutOff
java.lang.RuntimeException: Error processing arguments: Couldn't parse value from: 1.0 for setting: edgeCutOff
at org.cytoscape.command.internal.tunables.CommandTunableInterceptorImpl.validateAndWriteBackTunables(CommandTunableInterceptorImpl.java:96)
at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:82)
at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:180)
at org.cytoscape.command.internal.CommandExecutorImpl.handleCommand(CommandExecutorImpl.java:221)
at org.cytoscape.command.internal.CommandExecutorImpl.executeList(CommandExecutorImpl.java:158)
at org.cytoscape.command.internal.CommandStringsExecutorTask.run(CommandStringsExecutorTask.java:50)
at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
at org.cytoscape.work.SynchronousTaskManager$pbryglu.execute(Unknown Source)
at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.runClusterMaker(CreateAnnotationSetTask.java:107)
at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.run(CreateAnnotationSetTask.java:62)
at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by KevinMaroney** [comment]
Any update on this? I've also run into this problem just recently.

**Comment by mikekucera** [comment]
This is caused by a bug in Cytoscape. 

If you use one of the clusterMaker edge-weighted algorithms, like MCL (which is the default), and all the edges in the edge table have the same value for the "Edge Weight" column, then it throws that exception. 

The workaround is to set the "Edge Weight" column to "--None--".

**Comment by mikekucera** [comment]
I'm not able to fix the actual bug because its caused by an interaction between clusterMaker2 and Cytoscape. Instead AA now catches the exception and shows the user a pop-up explaining what went wrong and how to work around it. I'm afraid that's the best that can be done.
