### ISSUE TITLE
Fuzzy c-means doesn't work.

### ISSUE THREAD

**Issue by mikekucera** [BaderLab/AutoAnnotateApp#42]
java.lang.NullPointerException
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.AbstractFuzzyNetworkClusterer.createFuzzyTable(AbstractFuzzyNetworkClusterer.java:39)
    at edu.ucsf.rbvi.clusterMaker2.internal.algorithms.networkClusterers.FCM.FCMCluster.run(FCMCluster.java:193)
    at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:90)
    at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:180)
    at org.cytoscape.command.internal.CommandExecutorImpl.handleCommand(CommandExecutorImpl.java:221)
    at org.cytoscape.command.internal.CommandExecutorImpl.executeList(CommandExecutorImpl.java:158)
    at org.cytoscape.command.internal.CommandStringsExecutorTask.run(CommandStringsExecutorTask.java:50)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
    at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
    at org.cytoscape.work.SynchronousTaskManager$pbryglu.execute(Unknown Source)
    at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.runClusterMaker(CreateAnnotationSetTask.java:114)
    at org.baderlab.autoannotate.internal.task.CreateAnnotationSetTask.run(CreateAnnotationSetTask.java:63)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
Test every algorithm.

**Comment by mikekucera** [comment]
Its broken in clusterMaker2. Removing from the list.
