### ISSUE TITLE
trying to save collapsed annotated network throws error

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#51]
java.lang.IllegalArgumentException: edge is not contained in parent network.
    at org.cytoscape.model.internal.CySubNetworkImpl.addEdge(CySubNetworkImpl.java:173)
    at org.cytoscape.group.internal.CyGroupImpl.expand(CyGroupImpl.java:883)
    at org.baderlab.autoannotate.internal.task.CollapseTask.lambda$1(CollapseTask.java:106)
    at org.baderlab.autoannotate.internal.model.ModelManager.ignoreViewChangeWhile(ModelManager.java:153)
    at org.baderlab.autoannotate.internal.task.CollapseTask.expand(CollapseTask.java:103)
    at org.baderlab.autoannotate.internal.task.CollapseTask.run(CollapseTask.java:63)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

After error was able to save session by clicking on save again.  (might have been a concurrancy issue.  Also not the first time this error has come up.  I saw it multiple times yesterday but I am not able to reproduce it)

**Comment by risserlin** [comment]
didn't save correctly.  On reopen there are not networks listed in the network panel but all three networks seem to be there. 
Attached session as zip (just changed cys to zip so github would allow me to upload it) 
[example_cytoscape_publications broken.zip](https://github.com/BaderLab/AutoAnnotateApp/files/282476/example_cytoscape_publications.broken.zip)

**Comment by chrtannus** [comment]
The problem here is that the file **apps/org.cytoscape.swing-application/network_list.xml** was not created in the cys file, probably because the _IllegalArgumentException_ prevented it from being created when the session was being saved. Without this file, the Network panel can't be restored.
We could change Cytoscape to recreate it anyway, since it can retrieve the registered networks even without that file. The only information lost would be the networks order.
However I'm wondering if something else is also missing from the session file, so the proper fix would be to prevent that _CyGroup_ error from happening in the first place.

**Comment by chrtannus** [comment]
Also see: http://code.cytoscape.org/redmine/issues/3608
