### ISSUE TITLE
get error sometimes after collapsing annotations and try to redo layout

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#54]
Annotate network
collapse annotations
re-apply default layout
![image](https://cloud.githubusercontent.com/assets/3842763/15556457/ed8d3518-229b-11e6-89c0-d00254865677.png)

java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.IllegalArgumentException: unrecognized (table entry): Node suid: 1556
 (table name): USER
        at org.cytoscape.model.internal.DefaultTablesNetwork.getRow(DefaultTable
sNetwork.java:118)
        at org.cytoscape.model.internal.CySubNetworkImpl.getRow(CySubNetworkImpl
.java:62)
        at org.cytoscape.model.internal.DefaultTablesNetwork.getRow(DefaultTable
sNetwork.java:95)
        at org.cytoscape.model.internal.CySubNetworkImpl.getRow(CySubNetworkImpl
.java:62)
        at org.cytoscape.view.layout.LayoutPartition.addNode(LayoutPartition.jav
a:154)
        at org.cytoscape.view.layout.PartitionUtil.traverse(PartitionUtil.java:1
74)
        at org.cytoscape.view.layout.PartitionUtil.partition(PartitionUtil.java:
130)
        at org.cytoscape.view.layout.AbstractPartitionLayoutTask.doLayout(Abstra
ctPartitionLayoutTask.java:178)
        at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.j
ava:156)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:342)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:355)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
Can't reproduce this.
