### ISSUE TITLE
save autoannotated collapsed network barfs

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#56]
collapsed autoannotate network
save network
gets stuck "Expand Cluster:defense response virus"

There are  two dialogs that appear though (maybe deadlocks?) 
![screen shot 2016-05-30 at 10 23 50 am](https://cloud.githubusercontent.com/assets/3842763/15651923/a3c2c2b4-2650-11e6-94e0-e84b6291f5a6.png)

and has the follownig stack:
java.lang.NullPointerException
    at sun.java2d.pipe.LoopPipe.fillSpans(LoopPipe.java:336)
    at sun.java2d.pipe.LoopPipe.draw(LoopPipe.java:204)
    at sun.java2d.pipe.PixelToParallelogramConverter.draw(PixelToParallelogramConverter.java:148)
    at sun.java2d.SunGraphics2D.draw(SunGraphics2D.java:2497)
    at org.cytoscape.graph.render.immed.GraphGraphics.drawSimpleEdgeFull(GraphGraphics.java:1373)
    at org.cytoscape.graph.render.immed.GraphGraphics.drawEdgeFull(GraphGraphics.java:1167)
    at org.cytoscape.graph.render.stateful.GraphRenderer.renderGraph(GraphRenderer.java:468)
    at org.cytoscape.ding.impl.DGraphView.renderSubgraph(DGraphView.java:1882)
    at org.cytoscape.ding.impl.InnerCanvas.renderSubgraph(InnerCanvas.java:1004)
    at org.cytoscape.ding.impl.InnerCanvas.updateSubgraph(InnerCanvas.java:990)
    at org.cytoscape.ding.impl.DGraphView.handleEvent(DGraphView.java:2801)
    at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:120)
    at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:177)
    at org.cytoscape.group.internal.CyGroupImpl.collapse(CyGroupImpl.java:760)
    at org.baderlab.autoannotate.internal.task.CollapseTask.lambda$0(CollapseTask.java:78)
    at org.baderlab.autoannotate.internal.model.ModelManager.ignoreViewChangeWhile(ModelManager.java:153)
    at org.baderlab.autoannotate.internal.task.CollapseTask.collapse(CollapseTask.java:69)
    at org.baderlab.autoannotate.internal.task.CollapseTask.run(CollapseTask.java:61)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
    at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.io.tmpdir: [/Users/risserlin/CytoscapeConfiguration/3/karaf_data/tmp]

**Comment by mikekucera** [comment]
Hi Ruth, do you have a session file for this?

**Comment by risserlin** [comment]
no.  It barfed before it saved :(.  I had to force quit cytoscape.

**Comment by mikekucera** [comment]
I can't reproduce this.

Also the stack doesn't seem relevant. The clusters are all expanded before the session is saved but the stack is coming from a task that is trying to collapse a cluster. Also the TaskManager handles exceptions. I'm guessing it has nothing to do with the freezing and might have just been in the console.
