### ISSUE TITLE
Moving annotated cluster around - cytoscape freezes, no recovery

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#7]
randomly moving a cluster around and cytoscape freezes.  Only way to rescue is to close cytoscape and reopen.

**Comment by risserlin** [comment]
here is the stack that might be associated with this error:
java.lang.NullPointerException
    at org.cytoscape.ding.impl.ArbitraryGraphicsCanvas.drawCanvas(ArbitraryGraphicsCanvas.java:253)
    at org.cytoscape.ding.impl.DGraphView.drawSnapshot(DGraphView.java:1752)
    at org.cytoscape.ding.impl.DGraphView.drawSnapshot(DGraphView.java:1782)
    at org.cytoscape.ding.impl.BirdsEyeView.updateSubgraph(BirdsEyeView.java:314)
    at org.cytoscape.ding.impl.DGraphView.handleEvent(DGraphView.java:2770)
    at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:120)
    at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:177)
    at org.cytoscape.event.internal.CyEventHelperImpl$1.run(CyEventHelperImpl.java:70)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mikekucera** [comment]
I cannot reproduce this anymore. I've been moving things around for like an hour and it doesn't freeze.

Ruth, if this happens to you again can you please do the following:
- get the PID of the cytoscape java process
  - ps -A | grep java
  - or if that doesn't work use Activity Monitor to get the pid
- get a thread dump from the JVM
  - jstack &lt;pid&gt; >> threads.log

thanks.

**Comment by risserlin** [comment]
Did you make any changes in the version you are using?  If so can you send me the latest version so I can try it out.
Thanks, Ruth

**Comment by risserlin** [comment]
froze on windows.  
Here is the threads.log file
[threads.txt](https://github.com/BaderLab/AutoAnnotateApp/files/95172/threads.txt)

**Comment by mikekucera** [comment]
Yep, its a deadlock between two threads. Thanks.

**Comment by mikekucera** [comment]
This _should_ be fixed as one of the locks involved in the deadlock no longer exists. If the freeze happens again please reopen this issue. I will create another build shortly.

**Comment by risserlin** [comment]
I am still having this issue.  I am not sure if it is just on Windows or if it is on both my Mac and Windows but it keeps freezing on my windows box. I have multiple sessions of auto annotate open (this one crashed in my 3rd cytoscape instance)
[threads_crash2.txt](https://github.com/BaderLab/AutoAnnotateApp/files/123698/threads_crash2.txt)

**Comment by risserlin** [comment]
oops,  sorry that wasn't the thread file of the cytoscape instance that crashed.  Here is the one that froze 
[threads_crash3.txt](https://github.com/BaderLab/AutoAnnotateApp/files/123702/threads_crash3.txt)

**Comment by risserlin** [comment]
and now it crashed on windows with only one cytoscape session opened. 
[threads_crash4.txt](https://github.com/BaderLab/AutoAnnotateApp/files/123723/threads_crash4.txt)

**Comment by risserlin** [comment]
keeps happening.  Here is another one :) 
[threads_crash5.txt](https://github.com/BaderLab/AutoAnnotateApp/files/124851/threads_crash5.txt)

**Comment by risserlin** [comment]
the frequency of freezing kept increasing to the point that my first annotate selection would freeze cytoscape.  I delete my ~/Cytoscapeconfiguration directory and it seems to have fixed it for now (until next time)

**Comment by mikekucera** [comment]
So this time it was a deadlock between the AWT Event Dispatch Thread (EDT) and the EventBus synchronizer. 

Basically sometimes a cytoscape event will fire on the EDT. When it does it first flushes any payload events on the EDT (in this case ViewChangedEvent). 
Background: Cytoscape events are handled by the ModelManager class which processes the events and in turn fires more high level ModelEvents over the EventBus.
Thread 1) Cytoscape events fired on the EDT already have the EDT lock. When the ModelManager reacts and fires a ModelEvent it blocks waiting for the EventBus lock.
Thread 2) Cytoscape events fired on a worker thread. ModelManager reacts and fires a ModelEvent, which aquires the EventBus lock. Renderer reacts to ModelEvent and tries to draw an annotation. The addAnnotation() method calls invokeAndWait which blocks waiting on the EDT lock.

In order to reproduce this I had to write an App that just starts a thread that continuously flushes payoad events on the EDT. With that running in the background just clicking a node causes cytoscape to freeze.

My solution is to detect when payload events are on the EDT and fire the ModelEvent on a separate thread. That immediately releases the EDT lock. No more freezing.
